// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzamvllawrbafvadwvxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YW12bGxhd3JiYWZ2YWR3dnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1ODY4ODQsImV4cCI6MjA1MTE2Mjg4NH0.fKIxbkaFvGdp5G0W4sOrAN9dOV0EVIukPaKCuqVTJEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);